// Full tutorial through actual forms; the host and demo write only temporary data.
const assert = require('node:assert/strict');
const fs = require('node:fs');
const os = require('node:os');
const path = require('node:path');
const {spawn} = require('node:child_process');
const {chromium} = require(process.env.KVT_PLAYWRIGHT_MODULE || 'playwright');
const repo = path.resolve(__dirname, '..');
const root = fs.mkdtempSync(path.join(os.tmpdir(), 'kvt-demo-browser-'));
const env = {...process.env, KVT_HOME:root, PYTHONDONTWRITEBYTECODE:'1'};
delete env.KVT_DEMO_TOKEN;
const host = spawn(process.env.KVT_TEST_PYTHON || path.join(repo, 'build/win64-venv/Scripts/python.exe'), ['-B', 'tests/demo_host.py'], {cwd:repo, env, windowsHide:true, stdio:'ignore'});
let browser, context, base;
const sleep = ms => new Promise(resolve => setTimeout(resolve, ms));
(async () => {
  for (let count=0; count<200 && !fs.existsSync(path.join(root, 'host-ready.json')); count++) await sleep(100);
  assert.ok(fs.existsSync(path.join(root, 'host-ready.json')), 'Host did not start');
  base = 'http://127.0.0.1:' + JSON.parse(fs.readFileSync(path.join(root, 'host-ready.json'))).port;
  browser = await chromium.launch({headless:true, channel:'msedge'});
  context = await browser.newContext({viewport:{width:1440, height:1000}});
  // Existing chart libraries are unrelated to tutorial navigation; keep this test offline.
  await context.route('https://cdn.jsdelivr.net/**', route => route.fulfill({contentType:'application/javascript', body:'window.Chart = window.Chart || class { static register(){} constructor(){this.data={datasets:[]};this.options={};} update(){} destroy(){} };'}));
  const page = await context.newPage();
  const errors = [];
  page.on('pageerror', error => errors.push(error.message));
  page.setDefaultTimeout(12000);
  await page.goto(base + '/help');
  await page.locator('#help-search').fill('STARTTLS');
  assert.equal(await page.locator('.help-section:visible').count(), 1);
  await page.getByRole('button', {name:'Демо', exact:true}).click();
  await page.locator('.demo-panel').waitFor();
  await page.waitForURL('**/demo/project/**/');
  const prefix = new URL(page.url()).pathname.replace(/\/$/, '');
  const next = async index => {
    await page.waitForFunction(() => document.getElementById('demo-next') && !document.getElementById('demo-next').disabled);
    await page.locator('#demo-next').click();
    await page.waitForFunction(n => document.getElementById('demo-title')?.textContent.startsWith(n + '/'), index + 1);
  };
  await next(1);
  await page.locator('#demo-example').click();
  await page.locator('button[onclick="saveSystem()"]').click();
  await page.waitForFunction(() => document.getElementById('demo-status').textContent.includes('Шаг выполнен'));
  // Back preserves edits, repeat restores the checkpoint and clears downstream completion.
  await page.locator('#demo-repeat').click();
  await page.waitForFunction(() => document.getElementById('sys-name')?.value === 'Учебный склад');
  assert.equal(await page.locator('#demo-next').isDisabled(), true);
  await page.locator('#demo-example').click();
  await page.locator('button[onclick="saveSystem()"]').click();
  await next(2);
  await page.waitForFunction(() => document.getElementById('port-name')?.value === 'Учебная линия');
  await page.locator('#demo-example').click();
  await page.locator('button[onclick="saveSelectedPort()"]').click();
  await next(3);
  await page.locator('#demo-example').click();
  await page.locator('#modal-save-btn').click();
  await page.waitForFunction(() => document.getElementById('demo-next') && !document.getElementById('demo-next').disabled);
  assert.equal((await context.request.get(base + prefix + '/api/sensors')).ok(), true);
  const sensors = await (await context.request.get(base + prefix + '/api/sensors')).json();
  assert.equal(sensors.length, 4);
  await next(4);
  await page.locator('button[onclick="openEditModal(1)"]').click();
  await page.locator('#f-tmax').fill('26');
  await page.locator('#modal-save-btn').click();
  await next(5);
  await page.locator('#edit-mode-btn').click();
  await page.locator('button[onclick="saveTreeEditor()"]').click();
  await next(6);
  await page.locator('#mode-toggle').click();
  await page.locator('button[onclick="saveSensors()"]').click();
  await next(7);
  await page.locator('button[onclick="saveArchive()"]').click();
  await next(8);
  await page.locator('#demo-example').click();
  await page.locator('#notifications-form button[type=submit]').click();
  await next(9);
  await page.getByRole('button', {name:'+ Добавить группу', exact:true}).click();
  const group = page.locator('#notification-routing .form-section').last();
  await group.locator('input').first().fill('Учебная группа');
  await group.locator('summary').click();
  await group.locator('input[type=checkbox]').first().check();
  await group.locator('select').first().selectOption('custom');
  await group.getByRole('textbox', {name:'Почта группы: получатели через запятую'}).fill('group@example.com');
  await page.locator('#test-sensor').selectOption('1');
  await page.locator('[data-test=email]').click();
  await next(10);
  await page.locator('#demo-example').click();
  await page.locator('button[onclick="loadEvents()"]').click();
  await page.waitForFunction(() => document.getElementById('events-container').textContent.includes('Склад'));
  await next(11);
  await page.locator('#demo-example').click();
  await page.locator('button[onclick="saveOpcUa()"]').click();
  await next(12);
  await page.locator('#demo-example').click();
  await page.locator('button[onclick="saveMqtt()"]').click();
  await next(13);
  await next(14);
  const downloadPromise = page.waitForEvent('download');
  await page.locator('button[onclick="downloadBundle()"]').click();
  assert.ok((await downloadPromise).suggestedFilename().endsWith('.zip'));
  assert.ok(page.url().startsWith(base + prefix));
  await next(15);
  await page.locator('#demo-next').click();
  await page.waitForFunction(() => document.getElementById('demo-status').textContent.includes('16/16'));
  await page.screenshot({path:path.join(repo, 'build/demo-help.png'), fullPage:false});
  // Panel stays at the viewport bottom and does not cover the final content.
  const box = await page.locator('.demo-panel').boundingBox();
  assert.ok(Math.abs(box.y + box.height - 1000) <= 1);
  await page.locator('#demo-step').selectOption('8');
  await page.locator('#security').waitFor();
  await page.setViewportSize({width:430, height:850});
  await page.screenshot({path:path.join(repo, 'build/demo-mobile.png'), fullPage:false});
  await page.locator('#demo-exit').click();
  await page.waitForURL(base + '/');
  assert.equal(await page.locator('.demo-panel').count(), 0);
  assert.deepEqual(errors, []);
  console.log('16-step demo, help search, routing, repeat, export and responsive panel checks passed');
})().catch(error => {console.error(error); process.exitCode=1;}).finally(async () => {
  if (context && base) await context.request.post(base + '/demo/end').catch(() => {});
  if (browser) await browser.close();
  host.kill();
  await new Promise(resolve => host.exitCode === null ? host.once('exit', resolve) : resolve());
  fs.rmSync(root, {recursive:true, force:true});
});
